# Packer Configuration for macOS Sequoia VM in VMware Fusion

packer {
  required_plugins {
    vmware = {
      version = ">= 2.1.3"
      source  = "github.com/hashicorp/vmware"
    }
  }
}

# Define local variables
variable "vm_name" {
  type    = string
  default = "macos-sequoia"
}

variable "ssh_username" {
  type    = string
  default = "vagrant"
}

variable "ssh_password" {
  type    = string
  default = "vagrant"
}

source "vmware-iso" "macos" {
  # Path to the bootable macOS Sequoia ISO generated by build_sequoia_iso.sh
  iso_url      = "./Sequoia.iso"
  iso_checksum = "none"

  # VM hardware specifications
  vm_name       = var.vm_name
  guest_os_type = "darwin24-64" # Darwin 24 = macOS 15 Sequoia. Change to "darwin23-64" if using VMware Fusion 13.

  cpus                 = 4
  memory               = 8192
  disk_size            = 60000
  disk_adapter_type    = "nvme"
  network_adapter_type = "vmxnet3"

  # Network and SSH connection settings
  # Since Apple doesn't allow automated Setup Assistant skips easily, we set a high timeout.
  # Packer will wait for you to finish the OS installation and enable SSH manually before running provisioners.
  ssh_username = var.ssh_username
  ssh_password = var.ssh_password
  ssh_timeout  = "2h"

  # VNC configuration (used by Packer to send keystrokes)
  vnc_disable_password = true

  # Crucial VMX settings for running macOS guests on Intel Macs
  vmx_data = {
    "board-id.reflectHost"              = "FALSE"
    "hw.model.reflectHost"              = "FALSE"
    "serialNumber.reflectHost"          = "FALSE"
    "smc.present"                       = "TRUE"
    "firmware"                          = "efi"
    "keyboardAndMouse.connectAtPowerOn" = "TRUE"
    "usb.present"                       = "TRUE"
    "usb_xhci.present"                  = "TRUE"
  }

  # Boot Command Automation
  # The VM boots to the macOS Recovery partition on the ISO.
  # We automate selecting the language and launching Disk Utility.
  boot_wait = "50s" # Wait for Recovery OS to boot
  boot_command = [
    # 1. Select English and press Enter, then wait for the Recovery menu
    "<enter><wait15s>",

    # 2. Focus the menu bar (), navigate to "Utilities" menu (4 right arrows), open it, select "Terminal", and press Enter
    "<leftCtrlOn><f2><leftCtrlOff><wait2s>",
    "<right><wait><right><wait><right><wait><right><wait2s>",
    "<down><wait2s>",
    "<down><wait><enter><wait10s>",

    # 3. Format the virtual NVMe drive (disk0) as APFS named "Macintosh HD"
    "diskutil eraseDisk APFS \"Macintosh HD\" disk0<enter><wait15s>",

    # 4. Run the macOS Sequoia installer unattended on "Macintosh HD"
    "'/Volumes/Image Volume/Install macOS Sequoia.app/Contents/Resources/startosinstall' --volume '/Volumes/Macintosh HD' --agreetolicense --nointeraction<enter><wait5s>"
  ]

  shutdown_command = "sudo shutdown -h now"
}

build {
  sources = ["source.vmware-iso.macos"]

  # Provisioner to run AFTER you complete the OS installation and enable SSH
  provisioner "shell" {
    inline = [
      "echo '=== SSH Connected successfully! Starting VM provisioning ==='",

      # 1. Configure passwordless sudo for the vagrant user
      "echo 'vagrant' | sudo -S sh -c \"echo '${var.ssh_username} ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/vagrant\"",
      "sudo chmod 440 /etc/sudoers.d/vagrant",

      # 2. Prevent the machine from sleeping
      "sudo systemsetup -setsleep Never || true",
      "sudo systemsetup -setdisplaysleep Never || true",
      "sudo systemsetup -setcomputersleep Never || true",

      # 3. Disable password prompt for screen saver
      "defaults write com.apple.screensaver askForPassword -int 0 || true",

      # 4. Install Homebrew (standard helper for macOS Ansible environments)
      "echo '=== Installing Homebrew ==='",
      "NONINTERACTIVE=1 /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"",
      "echo 'eval \"$(/usr/local/bin/brew shellenv)\"' >> ~/.zprofile",
      "eval \"$(/usr/local/bin/brew shellenv)\"",

      "echo '=== VM Provisioning Complete ==='"
    ]
  }
}
