apiVersion: v2
name: vault-wrapper
description: A Helm wrapper chart for deploying HashiCorp Vault
type: application
version: 1.0.0
appVersion: "2.0.2"
dependencies:
  - name: vault
    version: 0.33.0
    repository: https://helm.releases.hashicorp.com
