apiVersion: v2
name: loki-wrapper
description: A Helm wrapper chart for deploying Grafana Loki
type: application
version: 1.0.0
appVersion: "3.7.3"
dependencies:
  - name: loki
    version: 18.4.0
    repository: https://grafana-community.github.io/helm-charts
